### ISSUE TITLE
Import .bibtex to zotero library

### ISSUE THREAD

**Issue by albert-ying** [dhondta/zotero-cli#11]
Hi, I'm wondering if it is possible to import .bibtex file to zotero from command line?

sth like `zotero-cli import xxx.bib`

Thank you!

**Comment by dhondta** [comment]
Hi !
In its current state, zotero-cli is only aimed to read from Zotero and not write to.
Moreover, in the other direction (exporting to BibTeX), this is already foreseen in the desktop application.
The objective of zotero-cli is only to filter, sort (if specified, with ranking) and export (XSLX, JSON, CSV, XML) references.
