### ISSUE TITLE
Feature request: Showcase more sort and export options

### ISSUE THREAD

**Issue by bjornasm** [dhondta/zotero-cli#16]
I think this tool looks really good! It would be great to have more export options (say to MD, HTML, text) and flexibility in what data you can export. However I do not know if that is outside of the focus of this.

**Comment by dhondta** [comment]
Hi @bjornasm !

Use the `export` command with the `--output-format` option. It already supports many formats.

```session
$ zotero-cli export --help
[...]
  -o {csv,html,json,md,pdf,rst,xml,xslx,yaml}, --output-format {csv,html,json,md,pdf,rst,xml,xslx,yaml}
                        output format (default: xslx)
[...]
```

Can you provide more information about what you mean with *more flexibility* ?

**Comment by bjornasm** [comment]
Hi, sorry for the a bit to sparse feature request. I realize that this might be better suited as a request to update the landing page on github to better showcase the amount of export options and sort options outside xlsx which is mentioned already. Thanks for a great versatile tool!
